import React from "react";
import { describe, expect, it, vi } from "vitest";
import { render, screen, within } from "@testing-library/react";
import { MLEngineDetail } from "../../components/forecast/ml-engine-detail";
import { StatisticalEngineDetail } from "../../components/forecast/statistical-engine-detail";
import { StatisticalCandidateTable } from "../../components/forecast/statistical-candidate-table";
import { ExecutiveComparison } from "../../components/forecast/forecast-horizon-table";
import { EngineComparison } from "../../components/forecast/engine-comparison";
import { horizonAccuracy, retrospectiveMetric, statisticalRanking } from "../../lib/statistical-preview-data";
import { productCandidate } from "../../lib/ml-preview-data";
import { addMonth, scopeHorizons, traderPoints } from "../../lib/forecast-chart-data";
import type { PreviewCandidate, PreviewScope } from "../../lib/forecast-preview";
import { emptyFilters } from "../../lib/supabase/types";

vi.mock("recharts", () => {
  const Box = ({ children }: { children?: React.ReactNode }) => <div>{children}</div>;
  return { ResponsiveContainer: Box, ComposedChart: Box, BarChart: Box, Bar: () => null, CartesianGrid: () => null, XAxis: () => null, YAxis: () => null, Tooltip: () => null, ReferenceArea: () => null, ReferenceLine: () => null, Area: () => null, Line: ({ dataKey }: { dataKey: string }) => <div data-testid={`line-${dataKey}`}/> };
});
const filters = { ...emptyFilters, chainId: "scope", productId: "product" };
const horizons = Array.from({ length: 12 }, (_, i) => ({ horizon: i + 1, target_period: addMonth("2026-07", i + 1), statistical_value: 10 + i, statistical_model: "Holt", ml_value: 15 + i, ml_model: "Random Forest Global", forecast_towell: 12 + i, p10: null, p50: 12 + i, p90: null, p95: null, classification: "Regular" }));
const stat: PreviewCandidate = { family: "statistical", product_id: "product", model: "Holt", retrospective_wape: 11, retrospective_bias: -2, observations: 12, status: "EVALUATED", by_horizon: [{ horizon: 1, wape: 11 }, { horizon: 3, wape: 12 }, { horizon: 6, wape: null }, { horizon: 12, wape: null }] };
const ml: PreviewCandidate = { family: "ml", model: "Random Forest Global", training_samples: 900, validation_observations: 24, observations: 24, retrospective_wape: 9, retrospective_bias: 1, trainable: true, validated: true, selected: true, operational_ready: true, status: "EVALUATED", by_horizon: [{ horizon: 1, wape: 9 }], by_product: [{ product_id: "product", retrospective_wape: 7, retrospective_bias: 2, observations: 12, by_horizon: [{ horizon: 1, wape: 7 }] }] };
const scope: PreviewScope = { chain_id: "scope", chain_name: "Synthetic scope", issue_period: "2026-07", status: "PREVIEW", mode: "RETROSPECTIVE_TRAINING", evaluation_mode: "RETROSPECTIVE_EVALUATION", eligibility: { evaluated: 45, stat_eligible: 20, ml_eligible: 20 }, statistical: { status: "COMPLETED", candidates: [stat], scope_candidates: [stat, { family: "statistical", model: "Holt-Winters", retrospective_wape: null, retrospective_bias: null, observations: 0, status: "NOT_APPLICABLE", reason: "REQUIRES_24_PERIODS" }], models: { Holt: 20 }, retrospective_wape: 30, retrospective_bias: -9 }, ml: { status: "COMPLETED", training_samples: 900, training_products: 6, features: ["lag 1", "horizonte"], leader: ml.model!, candidates: [{ ...ml, model: "Regresión Lineal Global", selected: false }, ml, { ...ml, model: "Gradient Boosting Global", selected: false }], retrospective_wape: 9, retrospective_bias: 1 }, selection: { published_champion: null, preview_leader: { strategy: "ensemble", retrospective_wape: 8, retrospective_bias: -1 }, preview_challenger: null, no_degradation: null, automatic_promotion: false }, products: [{ product_id: "product", product_code: "code", description: "Real contract fixture", category_id: null, forecast_status: "ACTIVE", horizons, statistical_model: "Holt", classification: "Regular" }], aggregates: horizons.map(h => ({ level: "chain", key: "scope", horizon: h.horizon, target_period: h.target_period, forecast_towell: h.forecast_towell * 10, statistical_value: h.statistical_value * 10, ml_value: h.ml_value * 10 })) };
const history = [{ period: "2026-07", sale: 0, order: 10, delivery: 8 }];
describe("E2.2A literal metrics and no fabrication", () => {
  it("new contract takes precedence, literal null does not fall back to stale validation", () => { expect(retrospectiveMetric({ retrospective_wape: null, validation_wape: 99 }, "wape")).toBeNull(); expect(retrospectiveMetric(stat, "wape")).toBe(11); });
  it("older renamed retrospective preview remains readable", () => { expect(retrospectiveMetric({ retrospective_validation_wape: 12 }, "wape")).toBe(12); expect(horizonAccuracy({ retrospective_validation_by_horizon: [{ horizon: 1, wape: 0 }] })).toEqual([{ horizon: 1, wape: 0 }]); });
  it("WAPE H1/H3/H6/H12 is separate from 12 operational months", () => { expect(horizonAccuracy(stat)).toHaveLength(4); expect(horizonAccuracy(stat)[2].wape).toBeNull(); expect(scopeHorizons(scope, filters)).toHaveLength(12); });
  it("not applicable candidate retains real reason and null metrics", () => { render(<StatisticalCandidateTable candidates={scope.statistical!.scope_candidates!} selected={null}/>); expect(screen.getByText("Holt-Winters")).toBeTruthy(); expect(screen.getByText("REQUIRES_24_PERIODS")).toBeTruthy(); expect(screen.getAllByText("—").length).toBeGreaterThan(1); });
  it("product WAPE uses rolling-origin metric not scope metric", () => { render(<StatisticalEngineDetail scope={scope} scopes={[scope]} filters={filters} historical={history} compareTowell={false} onCompare={vi.fn()}/>); expect(screen.getAllByText("11%").length).toBeGreaterThan(0); expect(screen.queryByText("30%")).toBeNull(); });
  it("scope ranking retains H1 metadata when endpoint omits individual horizons", () => { const s = { ...scope, products: scope.products!.map(p => ({ ...p, horizons: [] })) }; const ranking = statisticalRanking(s, { ...filters, productId: null }); expect(ranking[0].candidate?.retrospective_wape).toBe(11); render(<StatisticalEngineDetail scope={s} scopes={[s]} filters={{ ...filters, productId: null }} historical={[]} compareTowell={false} onCompare={vi.fn()}/>); expect(screen.getAllByText("Regular").length).toBeGreaterThan(0); expect(screen.queryByText("Resultado H1–H12 inconsistente")).toBeNull(); });
  it("backend aggregate Stat/ML literal values display without invented bands", () => { const h = scopeHorizons(scope, { ...filters, productId: null }); const p = traderPoints(history, [], h, scope.issue_period, filters); const first = p.find(r => r.period === "2026-08")!; expect(first).toMatchObject({ statistical: 100, ml: 150, towell: 120, band90: null, p50: null }); });
  it("scope statistical tab separates evaluated horizons from literal future months", () => { render(<StatisticalEngineDetail scope={{ ...scope, statistical: { ...scope.statistical!, selected_metrics: stat } }} scopes={[scope]} filters={{ ...filters, productId: null }} historical={history} compareTowell={false} onCompare={vi.fn()}/>); expect(screen.getByText("Backtest / validación retrospectiva")).toBeTruthy(); expect(screen.getByText("Forecast futuro · H1–H12")).toBeTruthy(); const table = screen.getAllByRole("table").at(-1)!; expect(within(table).getAllByRole("row")).toHaveLength(13); expect(within(table).getByText("2026-08")).toBeTruthy(); expect(within(table).getByText("2027-07")).toBeTruthy(); });
});
describe("E2.2A functional ML and future view", () => {
  it("ML global candidate scores never substitute missing product scores", () => { expect(retrospectiveMetric(productCandidate(ml, "product"), "wape")).toBe(7); expect(retrospectiveMetric(productCandidate(ml, "foreign"), "wape")).toBeNull(); });
  it("ML models and independent TRAINABLE/VALIDATED/SELECTED flags visible", () => { render(<MLEngineDetail scope={scope} scopes={[scope]} filters={filters} historical={history} horizons={horizons}/>); expect(screen.getByRole("heading", { name: "Machine Learning" })).toBeTruthy(); expect(screen.getByText("Regresión Lineal Global")).toBeTruthy(); expect(screen.getByText("Gradient Boosting Global")).toBeTruthy(); expect(screen.getByText("Trainable")).toBeTruthy(); expect(screen.getByText("Validated")).toBeTruthy(); expect(screen.getByText("Selected")).toBeTruthy(); expect(screen.getAllByText("900").length).toBeGreaterThan(0); expect(document.body.textContent).not.toMatch(/XGBoost|LightGBM|disponible en siguiente fase/); });
  it("ML future 12 months and only supplied baseline series", () => { render(<MLEngineDetail scope={scope} scopes={[scope]} filters={filters} historical={history} horizons={horizons}/>); const table = screen.getAllByRole("table").at(-1)!; expect(within(table).getAllByRole("row")).toHaveLength(13); expect(within(table).getByText("2026-08")).toBeTruthy(); expect(within(table).getByText("2027-07")).toBeTruthy(); expect(screen.getByTestId("line-ml")).toBeTruthy(); expect(screen.getByTestId("line-statistical")).toBeTruthy(); expect(screen.getByTestId("line-sale")).toBeTruthy(); });
  it("ML insufficient evaluation displays reason without invented forecast", () => { const s = { ...scope, ml: { ...scope.ml!, leader: null, candidates: [{ ...ml, retrospective_wape: null, validated: false, selected: false, reason: "INSUFFICIENT_TEMPORAL_FOLDS" }] } }; render(<MLEngineDetail scope={s} scopes={[s]} filters={filters} historical={history} horizons={horizons.map(h => ({ ...h, ml_value: null }))}/>); expect(screen.getByText("INSUFFICIENT_TEMPORAL_FOLDS")).toBeTruthy(); expect(screen.getByText(/Sin forecast ML H1–H12/)).toBeTruthy(); expect(screen.queryByTestId("line-ml")).toBeNull(); });
  it("all-chain ML view has independent rows and no global chart", () => { render(<MLEngineDetail scope={null} scopes={[scope, { ...scope, chain_id: "child", chain_name: "Child" }]} filters={emptyFilters} historical={[]} horizons={[]} cutsStatus="CUTS_NOT_ALIGNED"/>); expect(screen.getAllByRole("row")).toHaveLength(3); expect(screen.getByText("CUTS_NOT_ALIGNED")).toBeTruthy(); expect(screen.queryByTestId("line-ml")).toBeNull(); });
  it("future executive table is separate and visible Aug26–Jul27", () => { render(<ExecutiveComparison points={traderPoints(history, [], horizons, scope.issue_period, filters)} cutoff={scope.issue_period}/>); const tables = screen.getAllByRole("table"); expect(within(tables[0]).getAllByRole("row")).toHaveLength(13); expect(within(tables[0]).getByText("2026-08")).toBeTruthy(); expect(within(tables[0]).getByText("2027-07")).toBeTruthy(); expect(within(tables[0]).queryByText("2026-07")).toBeNull(); expect(within(tables[1]).getByText("2026-07")).toBeTruthy(); });
  it("consolidated comparison shows metrics and literal H1, never certification", () => { render(<EngineComparison scope={scope} horizons={horizons}/>); expect(screen.getByText("8%")).toBeTruthy(); expect(screen.getByText("Pronóstico H1")).toBeTruthy(); expect(screen.getByText("PREVIEW · No publicado")).toBeTruthy(); expect(document.body.textContent).not.toContain("WAPE certificado"); });
});
