"use client";
import { CartesianGrid, ComposedChart, Line, ReferenceArea, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { periodLabel, quantity, type TraderPoint } from "@/lib/forecast-chart-data";
export function StatisticalTooltip({ active, payload, compareTowell = false }: { active?: boolean; payload?: { payload: TraderPoint }[]; compareTowell?: boolean }) {
  const p = payload?.[0]?.payload;
  if (!active || !p) return null;
  return <div className="rounded-xl border bg-white p-3 shadow-xl"><p className="font-semibold">{periodLabel(p.period)}</p>{([["Venta real", p.sale], ["Forecast estadístico", p.statistical], ...(compareTowell ? [["Fcst Towell", p.towell]] : [])] as [string, number | null][]).filter(([, value]) => value !== null).map(([name, value]) => <p className="mt-2 text-xs" key={name}>{name}: {quantity(value)} pzas</p>)}</div>;
}
export function StatisticalForecastChart({ points, cutoff, compareTowell, onCompare }: { points: TraderPoint[]; cutoff?: string; compareTowell: boolean; onCompare: () => void }) {
  const future = points.filter(p => cutoff && p.period > cutoff);
  return <section className="rounded-xl border bg-white p-3 md:p-5"><div className="mb-4 flex flex-wrap justify-between gap-3"><h3 className="font-semibold">Real vs Forecast Estadístico</h3><label className="flex items-center gap-2 text-sm text-slate-600"><input type="checkbox" checked={compareTowell} onChange={onCompare}/>Comparar con Fcst Towell</label></div><p className="mb-3 text-xs text-slate-500">Venta real · Forecast estadístico seleccionado · Corte {periodLabel(cutoff)}</p><div className="h-[300px] md:h-[400px]" role="img" aria-label={`Real vs forecast estadístico; corte ${cutoff ?? "sin preview"}`}><ResponsiveContainer width="100%" height="100%" minWidth={0}><ComposedChart data={points} margin={{ top: 12, right: 18, left: 4, bottom: 10 }}><CartesianGrid vertical={false} stroke="#e2e8f0"/><XAxis dataKey="period" tickFormatter={periodLabel} minTickGap={30} tick={{ fontSize: 11 }}/><YAxis tickFormatter={quantity} width={72} tick={{ fontSize: 11 }}/>{future.length > 0 && <ReferenceArea x1={future[0].period} x2={future.at(-1)!.period} fill="#eff6ff"/>}{cutoff && <ReferenceLine x={cutoff} stroke="#2563eb" label={{ value: periodLabel(cutoff), position: "insideTopRight", fontSize: 11 }}/>}<Tooltip content={<StatisticalTooltip compareTowell={compareTowell}/>}/><Line dataKey="sale" name="Venta real" type="linear" stroke="#175cd3" strokeWidth={2} dot={false} connectNulls={false} isAnimationActive={false}/><Line dataKey="statistical" name="Forecast estadístico" type="linear" stroke="#0891b2" strokeWidth={3.2} dot={false} connectNulls={false} isAnimationActive={false}/>{compareTowell && <Line dataKey="towell" name="Fcst Towell" type="linear" stroke="#64748b" strokeWidth={1.5} strokeDasharray="5 4" dot={false} connectNulls={false} isAnimationActive={false}/>}</ComposedChart></ResponsiveContainer></div><p className="mt-3 text-xs text-slate-500">Vacíos ≠ cero. No se dibujan forecasts alternativos ni backtests que E2 no entrega.</p></section>;
}
