"use client";
import type { PreviewScope } from "@/lib/forecast-preview";
import type { Filters } from "@/lib/supabase/types";
import { percent, periodLabel, quantity, traderPoints, type HistoricalMonth } from "@/lib/forecast-chart-data";
import { finiteMetric, getStatisticalCandidates, metricEvidence, selectedStatisticalModel, selectionExplanation, statisticalCoverage, statisticalModelDistribution, statisticalRanking, statisticalStatus } from "@/lib/statistical-preview-data";
import { ForecastGrid } from "./forecast-horizon-table";
import { StatisticalModelDistribution } from "./statistical-model-distribution";
import { StatisticalCandidateTable } from "./statistical-candidate-table";
import { StatisticalHorizonAccuracy } from "./statistical-horizon-chart";
import { StatisticalForecastChart } from "./statistical-forecast-chart";
import { StatisticalHorizonTable } from "./statistical-horizon-table";

function KPIs({ rows }: { rows: [string, string][] }) { return <div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5">{rows.map(([label, value]) => <div className="rounded-xl border bg-white p-4" key={label}><p className="text-xs text-slate-500">{label}</p><p title={label.includes("WAPE") || label.includes("Bias") ? metricEvidence : undefined} className="mt-3 text-xl font-semibold">{value}</p></div>)}</div>; }
export function StatisticalEngineDetail({ scope, scopes, filters, historical, historyError, cutsStatus, compareTowell, onCompare }: { scope: PreviewScope | null; scopes: PreviewScope[]; filters: Filters; historical: HistoricalMonth[]; historyError?: boolean; cutsStatus?: string; compareTowell: boolean; onCompare: () => void }) {
  const selectedScope = scope?.chain_id === filters.chainId ? scope : null;
  if (!filters.chainId) return <section className="space-y-4"><h2 className="text-xl font-semibold">Motor Estadístico · Cobertura por cadena</h2><p className="text-sm text-slate-500">No se consolidan ni suman scopes parent/child.</p>{cutsStatus === "CUTS_NOT_ALIGNED" && <p className="text-xs text-blue-800">Cortes diferentes por cadena · CUTS_NOT_ALIGNED</p>}<ForecastGrid headers={["Cadena", "Corte", "Productos", "Stat elegibles", "Cobertura", "Modelo más seleccionado", "Status"]} rows={scopes.map(s => { const c = statisticalCoverage(s); return [s.chain_name ?? s.chain_id, periodLabel(s.issue_period), quantity(c.total), quantity(c.eligible), percent(c.percent), statisticalModelDistribution(s)[0]?.model ?? "—", statisticalStatus(s.error_code ?? s.status)]; })}/></section>;
  if (!selectedScope) return <p className="text-sm text-slate-500">Sin vista previa estadística para la cadena seleccionada.</p>;
  const product = selectedScope.products?.find(p => p.product_id === filters.productId && (!filters.categoryId || p.category_id === filters.categoryId));
  const distribution = statisticalModelDistribution(selectedScope), coverage = statisticalCoverage(selectedScope);
  if (!filters.productId) return <section className="space-y-5">
    <h2 className="text-xl font-semibold">Motor Estadístico · {selectedScope.chain_name ?? "Scope seleccionado"} · Corte {periodLabel(selectedScope.issue_period)}</h2>
    <KPIs rows={[["Productos evaluados", quantity(coverage.total)], ["Stat elegibles", quantity(coverage.eligible)], ["Cobertura", percent(coverage.percent)], ["Modelo más seleccionado", distribution[0]?.model ?? "—"], ["WAPE retrospectivo scope", percent(selectedScope.statistical?.retrospective_wape)], ["Bias retrospectivo scope", percent(selectedScope.statistical?.retrospective_bias)]]}/>
    <p className="text-xs text-slate-500">Cobertura y distribución del scope completo. Categoría y búsqueda filtran el ranking; no recalculan modelos.</p>
    <p className="text-sm text-slate-500">Modelos disponibles: {selectedScope.statistical?.available_candidates?.length ?? "—"} · {selectedScope.statistical?.available_candidates?.join(" · ") || "Sin catálogo disponible"}</p>
    <ForecastGrid headers={["Estado", "Productos"]} rows={Object.entries(selectedScope.eligibility ?? {}).map(([state, count]) => [({ visible_products: "Productos visibles", evaluated: "Evaluados", stat_eligible: "Elegibles Stat", ml_eligible: "Elegibles ML" }[state] ?? statisticalStatus(state.toUpperCase())), quantity(count)])}/>
    <StatisticalModelDistribution rows={distribution}/>
    <section><h3 className="mb-3 font-semibold">Ranking de modelos por producto</h3><ForecastGrid headers={["Producto", "Clasificación", "Modelo seleccionado", "WAPE", "Bias", "Obs"]} rows={statisticalRanking(selectedScope, filters).map(r => [r.product.description, r.product.horizons?.find(h => h.horizon === 1)?.classification ?? "—", r.selection.consistent ? r.selection.model! : "Resultado H1–H12 inconsistente", percent(r.candidate?.validation_wape), percent(r.candidate?.validation_bias), quantity(r.candidate?.observations)])}/></section>
  </section>;
  if (!product) return <p className="text-sm text-slate-500">El producto seleccionado no está incluido en este preview.</p>;
  const selection = selectedStatisticalModel(product, selectedScope.issue_period);
  const candidates = getStatisticalCandidates(selectedScope, product.product_id), candidate = candidates.find(c => c.model === selection.model);
  const first = product.horizons?.find(h => h.horizon === 1), classification = first?.classification;
  const intermittent = ["Croston", "SBA", "TSB"].includes(selection.model ?? "") && classification === "Intermitente";
  const points = traderPoints(historical, [], selection.horizons, selectedScope.issue_period, filters);
  return <section className="space-y-5"><div><h2 className="text-xl font-semibold">Motor Estadístico</h2><p className="mt-1 text-sm text-slate-500">{product.description} · {selectedScope.chain_name ?? "Scope seleccionado"} · Corte {periodLabel(selectedScope.issue_period)} · {statisticalStatus(first?.forecast_status ?? product.forecast_status)}</p>{intermittent && <span className="mt-2 inline-block rounded-full bg-blue-50 px-3 py-1 text-xs text-blue-800">Demanda intermitente</span>}</div><KPIs rows={[["Modelo seleccionado", selection.model ?? "—"], ["Clasificación", classification ?? "—"], ["WAPE validación retro", percent(finiteMetric(candidate?.validation_wape))], ["Bias validación retro", percent(finiteMetric(candidate?.validation_bias))], ["Observaciones", quantity(candidate?.observations)]]}/>{!(product.horizons?.length) ? <p className="rounded-xl border bg-white p-5 text-sm text-slate-500">Este producto no cuenta con evidencia suficiente para generar un forecast estadístico operativo. Estado: {statisticalStatus(product.forecast_status)}.</p> : !selection.consistent ? <p role="alert" className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">Resultado estadístico inconsistente: el modelo seleccionado debe coincidir en H1–H12, con doce horizontes válidos. No se dibuja un forecast parcial.</p> : <>{historyError && <p role="alert" className="text-sm text-rose-700">No fue posible consultar la venta histórica; no se sustituyen los datos.</p>}<StatisticalForecastChart points={points} cutoff={selectedScope.issue_period} compareTowell={compareTowell} onCompare={onCompare}/><p className="text-sm text-slate-500">{selectionExplanation(candidates, candidate)}</p></>}<div className="grid items-start gap-5 xl:grid-cols-2"><StatisticalCandidateTable candidates={candidates} selected={selection.model}/><StatisticalHorizonAccuracy candidate={candidate}/></div>{selection.consistent && <StatisticalHorizonTable horizons={selection.horizons}/>}</section>;
}
